export * from './Registration';
export * from './Login';
export * from './ForgetPhoneGetPhoneVerifyCode';
export * from './Start';
export * from './ForgetPhoneVerificationCode';
export * from './RegisterVerificationCode';
export * from './RegisterGetPhoneVerifyCode';
export * from './PasswordChange';
export * from './userComponents/AddPreference';
export * from './userComponents/Home';
export * from './userComponents/EditPreference';
export * from './Scan';
export * from './barCode';
export * from './userComponents/Profile';
export * from './userComponents/ProfileEdit';
export * from './userComponents/SearchPreference';
export * from './userComponents/ProfileEditPhone';
export * from './userComponents/ProfileVerifyPhone';
export * from './FoodFlagRed';
// export * from './FoodFlagGreen';
// export * from './FoodInfo';
